{
	"version": 1678885169,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/fundo10-sheet0.png",
		"images/fundo21-sheet0.png",
		"images/fundo31-sheet0.png",
		"images/fundo40-sheet0.png",
		"images/fundo50-sheet0.png",
		"images/fundo20-sheet0.png",
		"images/fundo30-sheet0.png",
		"images/fundo41-sheet0.png",
		"images/fundo51-sheet0.png",
		"images/fundo11-sheet0.png",
		"images/t01-sheet0.png",
		"images/t03-sheet0.png",
		"images/t04-sheet0.png",
		"images/t06-sheet0.png",
		"images/t08-sheet0.png",
		"images/t09-sheet0.png",
		"images/t10-sheet0.png",
		"images/t12-sheet0.png",
		"images/t02-sheet0.png",
		"images/t05-sheet0.png",
		"images/fx_tecla-sheet0.png",
		"images/fx_tecla-sheet1.png",
		"images/tsombra-sheet0.png",
		"images/sapo_o1-sheet0.png",
		"images/sapo_o1-sheet1.png",
		"images/sapo_o2-sheet0.png",
		"images/sapo_o2-sheet1.png",
		"images/fx_fundo-sheet0.png",
		"images/bt1-sheet0.png",
		"images/bt2-sheet0.png",
		"images/bt3-sheet0.png",
		"images/bt4-sheet0.png",
		"images/corda1-sheet0.png",
		"images/corda2-sheet0.png",
		"images/corda3-sheet0.png",
		"images/corda4-sheet0.png",
		"images/corda5-sheet0.png",
		"images/corda6-sheet0.png",
		"images/girafa_cabeca-sheet0.png",
		"images/girafa_cabeca-sheet1.png",
		"images/girafa_cabeca-sheet2.png",
		"images/girafa_cabeca-sheet3.png",
		"images/girafa_cabeca-sheet4.png",
		"images/estrela-sheet0.png",
		"images/estrela-sheet1.png",
		"images/estrela_linha-sheet0.png",
		"images/estrela_pivot-sheet0.png",
		"images/bt5-sheet0.png",
		"images/bt5-sheet1.png",
		"images/estrela1-sheet0.png",
		"images/estrela1-sheet1.png",
		"images/pino1-sheet0.png",
		"images/pino1-sheet1.png",
		"images/pino2-sheet0.png",
		"images/pino2-sheet1.png",
		"images/pino3-sheet0.png",
		"images/pino3-sheet1.png",
		"images/pino4-sheet0.png",
		"images/pino4-sheet1.png",
		"images/pino5-sheet0.png",
		"images/pino5-sheet1.png",
		"images/ovelha_cabeca-sheet0.png",
		"images/ovelha_cabeca-sheet1.png",
		"images/ovelha_cabeca-sheet2.png",
		"images/pino6-sheet0.png",
		"images/pino6-sheet1.png",
		"images/pino7-sheet0.png",
		"images/pino7-sheet1.png",
		"images/pino8-sheet0.png",
		"images/pino8-sheet1.png",
		"images/pino9-sheet0.png",
		"images/pino9-sheet1.png",
		"images/fx_fundo2-sheet0.png",
		"images/fx_fundo2-sheet1.png",
		"images/fx_fundo2-sheet2.png",
		"images/bateria2-sheet0.png",
		"images/bateria2-sheet1.png",
		"images/bateria3-sheet0.png",
		"images/bateria3-sheet1.png",
		"images/bateria4-sheet0.png",
		"images/bateria4-sheet1.png",
		"images/bateria5-sheet0.png",
		"images/bateria5-sheet1.png",
		"images/bateria1-sheet0.png",
		"images/bateria1-sheet1.png",
		"images/roda-sheet0.png",
		"images/fx-sheet0.png",
		"images/fx2-sheet0.png",
		"images/fx3-sheet0.png",
		"images/bateria6-sheet0.png",
		"images/bateria7-sheet0.png",
		"images/meleca-sheet0.png",
		"images/tartaruga_cabeca-sheet0.png",
		"images/tartaruga_cabeca-sheet1.png",
		"images/tartaruga_cabeca-sheet2.png",
		"images/tartaruga_cabeca-sheet3.png",
		"images/tartaruga_nadadeira-sheet0.png",
		"images/tartaruga_nadadeira-sheet1.png",
		"images/tartaruga_nadadeira-sheet2.png",
		"images/xlfn1-sheet0.png",
		"images/xlfn2-sheet0.png",
		"images/xlfn3-sheet0.png",
		"images/xlfn3-sheet1.png",
		"images/xlfn3-sheet2.png",
		"images/xlfn3-sheet3.png",
		"images/xlfn4-sheet0.png",
		"images/xlfn4-sheet1.png",
		"images/xlfn4-sheet2.png",
		"images/xlfn4-sheet3.png",
		"images/xlfn5-sheet0.png",
		"images/bolha-sheet0.png",
		"images/tartaruga_nadadeira2-sheet0.png",
		"images/tartaruga_nadadeira3-sheet0.png",
		"images/raio_luz-sheet0.png",
		"images/peixe-sheet0.png",
		"images/peixe-sheet1.png",
		"images/peixe-sheet2.png",
		"images/algas-sheet0.png",
		"images/seta-sheet0.png",
		"images/bt_musica1-sheet0.png",
		"images/bt_musica1-sheet1.png",
		"images/bt_sons-sheet0.png",
		"images/bt_sons-sheet1.png",
		"images/bt_musica2-sheet0.png",
		"images/bt_musica2-sheet1.png",
		"images/bt_musica3-sheet0.png",
		"images/bt_musica3-sheet1.png",
		"images/bt_musica4-sheet0.png",
		"images/bt_musica4-sheet1.png",
		"images/bt_musica5-sheet0.png",
		"images/bt_musica5-sheet1.png",
		"media/piano 1.ogg",
		"media/piano 10.ogg",
		"media/piano 11.ogg",
		"media/piano 12.ogg",
		"media/piano 2.ogg",
		"media/piano 3.ogg",
		"media/piano 4.ogg",
		"media/piano 5.ogg",
		"media/piano 6.ogg",
		"media/piano 7.ogg",
		"media/piano 8.ogg",
		"media/piano 9.ogg",
		"media/chocalho.ogg",
		"media/vai.ogg",
		"media/vem.ogg",
		"media/seta.ogg",
		"media/boing2.ogg",
		"media/zip.ogg",
		"media/1.ogg",
		"media/2.ogg",
		"media/3.ogg",
		"media/4.ogg",
		"media/a.ogg",
		"media/b.ogg",
		"media/c.ogg",
		"media/riso.ogg",
		"media/brilho.ogg",
		"media/gt1.ogg",
		"media/gt2.ogg",
		"media/gt3.ogg",
		"media/gt4.ogg",
		"media/gt5.ogg",
		"media/gt6.ogg",
		"media/t1.ogg",
		"media/t2.ogg",
		"media/t3.ogg",
		"media/t4.ogg",
		"media/t5.ogg",
		"media/x1.ogg",
		"media/x2.ogg",
		"media/x3.ogg",
		"media/x4.ogg",
		"media/x5.ogg",
		"media/gtt1.ogg",
		"media/gtt2.ogg",
		"media/gtt3.ogg",
		"media/gtt4.ogg",
		"media/gtt5.ogg",
		"media/gtt6.ogg",
		"media/bell 1.ogg",
		"media/bell 10.ogg",
		"media/bell 11.ogg",
		"media/bell 12.ogg",
		"media/bell 2.ogg",
		"media/bell 3.ogg",
		"media/bell 4.ogg",
		"media/bell 5.ogg",
		"media/bell 6.ogg",
		"media/bell 7.ogg",
		"media/bell 8.ogg",
		"media/bell 9.ogg",
		"media/b1.ogg",
		"media/b2.ogg",
		"media/b3.ogg",
		"media/b4.ogg",
		"media/b5.ogg",
		"media/b7.ogg",
		"media/b9.ogg",
		"media/tr1.ogg",
		"media/tr2.ogg",
		"media/tr3.ogg",
		"media/tr4.ogg",
		"media/tr5.ogg",
		"media/grito1.ogg",
		"media/grito4.ogg",
		"media/grito3.ogg",
		"media/grito2.ogg",
		"media/grito5.ogg",
		"media/bt2.ogg",
		"media/bt3.ogg",
		"media/bt5.ogg",
		"media/bt7.ogg",
		"media/bt4.ogg",
		"media/bt8.ogg",
		"media/bt9.ogg",
		"media/btr2.ogg",
		"media/btr3.ogg",
		"media/btr4.ogg",
		"media/btr6.ogg",
		"media/btr7.ogg",
		"media/btr8.ogg",
		"media/btr9.ogg",
		"media/org1.ogg",
		"media/org10.ogg",
		"media/org11.ogg",
		"media/org12.ogg",
		"media/org2.ogg",
		"media/org3.ogg",
		"media/org4.ogg",
		"media/org5.ogg",
		"media/org6.ogg",
		"media/org7.ogg",
		"media/org8.ogg",
		"media/org9.ogg",
		"media/pi1.ogg",
		"media/pi2.ogg",
		"media/pi3.ogg",
		"media/pi4.ogg",
		"media/pi5.ogg",
		"media/vibra1.ogg",
		"media/vibra2.ogg",
		"media/vibra3.ogg",
		"media/vibra4.ogg",
		"media/vibra5.ogg",
		"media/banjo1.ogg",
		"media/banjo2.ogg",
		"media/banjo3.ogg",
		"media/banjo4.ogg",
		"media/banjo5.ogg",
		"media/banjo6.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}